### PR TITLE
Add outLodashPackage feature to allow for lodash-es, fix .cjs and .mjs files.

### PR DESCRIPTION
**Pull request by mbullington**
Hello! Thanks for your work on `esbuild-plugin-lodash` it's really nice.

In using it I found a few issues I wanted to contribute back.

- Make sure `.cjs`/`.mjs` files are treated in the same way as `.js` (this is what ESBuild itself does), and not trying to find a special loader for `cjs`/`mjs`.
- I added an option `outLodashPackage` so, if wanted, a user could overwrite calls from `lodash` to use `lodash-es`.

### CODE REVIEW

**Comment by josteph** [comment]
Hey, thanks for the PR!

Adding `outLodashPackage` seems to be a bit overkill, if the user has `lodash-es` installed instead of `lodash`, this library would have no purpose anymore because it only tries to eliminate the side-effects from non-es `lodash`. Can you clarify more about the use case for this option?

**Comment by mbullington** [comment]
Hey @josteph !

This is a good assumption to question. The reason I added `outLodashPackage` was for parity with https://github.com/jaredpalmer/tsdx#using-lodash , according to this doc `@types/lodash` is more mature than `@types/lodash-es`. Thus developers may want to use that over `lodash-es` but still benefit from ESM tree-shaking.

If that's still the case with `@types/lodash-es` I'm not sure.

**Comment by josteph** [comment]
Thanks for the good explanation, I didn't know such thing happened with `@types/lodash-es` 😅

**Comment by josteph** [comment]
Released [v1.1.0](https://github.com/josteph/esbuild-plugin-lodash/compare/1.0.4...1.1.0)

**Pull request merged**
